### ISSUE TITLE
Settings to hide group header

### ISSUE THREAD

**Issue by benedekh** [esvit/ng-table#982]
Hello,

As I upgraded from 0.8.3 to 1.0.0 a group header appeared above my table, that I cannot make disappear. The only solution I found so far was to hide that CSS class, but it is only a workaround for the problem.

```css
.ng-table-group-header {
	display: none;
}
```

Is there any setting that hides this header even if I have a group(By) argument in NgTableParams?

Thank you for the answer in advance.
